- hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
  - name: Install nginx
    yum:
      name: nginx
      state: present
  - name: Start service
    service:
      name: nginx
      state: started
  - name: Copy file
    copy:
      src: /home/ubuntu/index.html
      dest: /var/www/html/index.html
      mode: '777'